# golangci-lint configuration with strict presets
run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - deadcode
    - dupl
    - errname
    - errorlint
    - exportloopref
    - exhaustive
    - forbidigo
    - funlen
    - gochecknoinits
    - gocognit
    - gocyclo
    - goerr113
    - goheader
    - gomnd
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - ifshort
    - importas
    - interfacer
    - makezero
    - maligned
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - promlinter
    - rowserrcheck
    - scopelint
    - sqlclosecheck
    - stylecheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - funlen
        - gocognit
  max-issues-per-linter: 0
  max-same-issues: 0

