# GoReleaser configuration for cross-platform releases
project_name: req

before:
  hooks:
    - go mod download

builds:
  - id: req
    main: ./cmd/req
    binary: req
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -ldflags=-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.buildDate={{.Date}}

archives:
  - id: default
    builds:
      - req
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

